workflows:
  motiva-ios-testflight-workflow:
    name: Motiva iOS Build and Publish to TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: noourway

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        provisioning_profiles:
          - motiva_Manual_Profile
        certificates:
          - ios_cert_manual

    scripts:
      - name: Clean and Get Dependencies
        script: |
          flutter clean
          flutter pub get

      # هذا الأمر هو الحل الأساسي لتعطيل محاولة الـ Swift Package Manager
      - name: Disable Swift Package Manager
        script: |
          flutter config --no-enable-swift-package-manager

      - name: Apply Vault Profiles
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          # إضافة flag لضمان عدم تفعيل SPM أثناء البناء
          flutter build ipa --release --no-enable-swift-package-manager --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - codexus.eg@gmail.com
