workflows:
  motiva-ios-testflight-workflow:
    name: Motiva iOS Build and Publish to TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: noourway

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        provisioning_profiles:
          - motiva_Manual_Profile
        certificates:
          - ios_cert_manual

    scripts:
      - name: Clean Project
        script: |
          flutter clean
          flutter pub get

      - name: Force Disable SPM in Xcode
        script: |
          # هذا الأمر يدخل داخل ملفات Xcode ويغلق ميزة SPM نهائياً من الجذور
          sed -i '' 's/attributes = {/attributes = {\n\t\t\t\tDisableSwiftPackageIntegration = YES;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Prepare iOS Environment
        script: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod install
          cd ..

      - name: Apply Vault Profiles
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - codexus.eg@gmail.com
