/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBn9EmdljXeize3u6YuCambUgvylQXnqo',
    appId: '1:257633657471:web:ee824e26f494286eac554a',
    messagingSenderId: '257633657471',
    projectId: 'motiva-6b2ef',
    authDomain: 'motiva-6b2ef.firebaseapp.com',
    storageBucket: 'motiva-6b2ef.firebasestorage.app',
    measurementId: 'G-T7D5FGXWZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWoT3sVlbtQAOEcrW7ojSOEmUqYh1nKvo',
    appId: '1:257633657471:android:f296f2977c37132dac554a',
    messagingSenderId: '257633657471',
    projectId: 'motiva-6b2ef',
    storageBucket: 'motiva-6b2ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpI_X2PB2ZyhU42MWNHrYucYcAGuvM3Pc',
    appId: '1:257633657471:ios:79cd929f0fc16ca5ac554a',
    messagingSenderId: '257633657471',
    projectId: 'motiva-6b2ef',
    storageBucket: 'motiva-6b2ef.firebasestorage.app',
    iosBundleId: 'com.tajera.motiva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBn9EmdljXeize3u6YuCambUgvylQXnqo',
    appId: '1:257633657471:web:a2542f0df067ee29ac554a',
    messagingSenderId: '257633657471',
    projectId: 'motiva-6b2ef',
    authDomain: 'motiva-6b2ef.firebaseapp.com',
    storageBucket: 'motiva-6b2ef.firebasestorage.app',
    measurementId: 'G-08SDCLS5ZS',
  );
}
*/
